### ISSUE TITLE
Running overlay.sh at boot time.

### ISSUE THREAD

**Issue by xresende** [lnls-sirius/pru-serial485#4]
Is is possible for the system to configure its pins to PRU automatically at boot time? Maybe a linux daemon that runs overlay.sh once. Having to remember to execute it manually before running the IOC is prone to errors, I think. Maybe we can do this latter, for the deployment version for Sirius.

**Comment by pnallin** [comment]
It is already done automatically in Controls BBB. There is a file (/etc/rc.local) that runs every time at BBB booting, and overlay.sh is there. I added this comment to readme file in case someone else wants to configure/install/use PRUserial485 in another BBB.
